service: text-analyzer
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  textAnalyzer:
    handler: handler.textAnalyzer
    events:
      - http:
          path: /text-analyzer
          method: POST

